// SPDX-License-Identifier: MIT
// GENERATED by scripts/capture-schema.py from just_ai_i18n_docgen.appmeta:AppBase — do not edit by hand.
// Each table's DDL is the exact text Python's create_all writes to sqlite_master;
// `columns` carries what lives in Python, not the database: the conversion kind and
// the Python-side defaults. Re-generate when a Python table changes.
export const TABLES = [
  {
    "name": "app_settings",
    "ddl": "CREATE TABLE app_settings (\n\t\"key\" VARCHAR NOT NULL, \n\tvalue VARCHAR, \n\tPRIMARY KEY (\"key\")\n)",
    "indexes": [],
    "columns": {
      "key": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "value": {
        "kind": "text"
      }
    }
  }
];
